name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify settings before Docker build
        run: |
          echo "Git commit:"
          git rev-parse HEAD

          echo "Settings file:"
          grep -nE 'DEBUG|ALLOWED_HOSTS' employee_mgmt/settings.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image
        run: |
          docker tag \
            ${{ vars.ECR_REPOSITORY }}:latest \
            985016028963.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
            985016028963.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest
